Specify min version of MacOS for clean env tests
trikset/trik-studio pull request #1073
Opened 2020-08-25 11:52 UTC by anastasiia-kornilova

Need to check our requirements

2020-08-25 18:39 UTC, iakov requested changes
Попробуй так. Или `python3@3.7`, но тебе же и 3.8 подойдёт.

2020-08-25 18:39 UTC, iakov commented on .travis.yml
> +      - env HOMEBREW_NO_AUTO_UPDATE=1 brew install p7zip python3
```suggestion
      - env HOMEBREW_NO_AUTO_UPDATE=1 brew install p7zip python@3.7
```

2020-08-25 18:58 UTC, anastasiia-kornilova commented
> Попробуй так. Или `python3@3.7`, но тебе же и 3.8 подойдёт.

Спасиб!

2020-08-26 10:57 UTC, anastasiia-kornilova commented
It was decided to test on Big Sierra which is default one for travis now

2020-08-26 10:57 UTC, closed without merging