Fix twoDModel runner
trikset/trik-studio pull request #1092
Opened 2020-09-03 19:29 UTC by khodand

- Show model widgets
- New `--close-on-success` option

2020-09-04 06:24 UTC, iakov requested changes
Небольшие правки. Обнови и надо обсудить.

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/main.cpp
> +								, "mode", "diagram");
```suggestion
	QCommandLineOption modeOption({"m", "mode"}, QObject::tr("Set to \"script\" for"\
								"execution of js/py from the project or set to \"diagram\" for block diagram.")
								, "mode", "diagram");
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/main.cpp
> +								   , QObject::tr("The model will be closed if the program finishes without errors."));
```suggestion
								   , QObject::tr("Close the window and exit if the diagram/script finishes without errors."));
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.cpp
> +	for (const auto &defaultSettingsFile : mPluginFacade.defaultSettingsFiles()) {
```suggestion
	for (auto &&defaultSettingsFile : mPluginFacade.defaultSettingsFiles()) {
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.cpp
> +	for (const auto widget : QApplication::allWidgets()) {
```suggestion
	for (auto &&widget : QApplication::allWidgets()) {
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.cpp
> +	for (const auto twoDModelWindow : twoDModelWindows) {
```suggestion
	for (auto &&twoDModelWindow : twoDModelWindows) {
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.cpp
> +			if (layout) {
```suggestion			
			qReal::ui::ConsoleDock* console = nullptr;
			if (auto layout = dynamic_cast<QGridLayout*>(twoDModelWindow->layout())) {
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.cpp
> +			for (const auto robotModel : twoDModelWindow->model().robotModels()) {
```suggestion
			for (auto &&robotModel : twoDModelWindow->model().robotModels()) {
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/checker/twoDModelRunner/runner.h
> +				   , const int customSpeedFactor, const bool closeOnSuccess, const bool showConsole);
```suggestion
	bool interpret(const QString &saveFile, bool background, int customSpeedFactor, bool closeOnSuccess, bool showConsole);
```

2020-09-04 06:24 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/twoDModelEngineFacade.cpp
> -	mView->setParent(dockInterface.windowWidget());
Интересно... А кто тут будет родителем?

2020-09-04 07:25 UTC, iakov requested changes
Надо переводы обновить.

2020-09-04 09:05 UTC, iakov requested changes

2020-09-04 09:05 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/twoDModelEngineFacade.cpp
> -	mView->setParent(dockInterface.windowWidget());
Тут мешает QScopedPointer. Лучше сделать mView обычным указателем и добавлять родителя виджету. Родительский виджет удалит его.

2020-09-04 09:25 UTC, khodand commented on plugins/robots/common/twoDModel/src/engine/twoDModelEngineFacade.cpp
> -	mView->setParent(dockInterface.windowWidget());
Рисоваться он все равно не будет, потому что `dockInterface.windowWidget()` скрытый по умолчанию, а если `dockInterface.windowWidget()->show()`, то отобразятся какие-то странные элементы `windowWidget`. Их видимо надо руками скрывать где-то.

2020-09-04 09:28 UTC, khodand commented on plugins/robots/common/twoDModel/src/engine/twoDModelEngineFacade.cpp
> -	mView->setParent(dockInterface.windowWidget());
Не понимаю в чем проблема с отсутствием родителя и ScopedPointer-ом.

2020-09-04 11:17 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/twoDModelEngineFacade.cpp
> -	mView->setParent(dockInterface.windowWidget());
Потому что код, который ты поменял, относится к основной студии. Возможно, надо что-то порефакторить. Но родительский виджет должен быть. https://doc.qt.io/qt-5/qwidget.html#details

2020-09-06 09:56 UTC, iakov approved these changes

2020-09-06 10:48 UTC, merged