Delete blocks and scene elements on backspace
trikset/trik-studio pull request #1118
Opened 2020-09-25 00:43 UTC by khodand

Fix #1110

2020-09-25 06:02 UTC, iakov requested changes

2020-09-25 06:02 UTC, iakov commented on qrgui/editor/editorViewScene.cpp
> +	mActionDeleteFromDiagram.setShortcuts(QList<QKeySequence>()
С другой стороны, лучше использовать готовые `QKeySequence::Delete` и `QKeySequence::Backspace`. Но последняя, похоже, не про кнопку Backspace. Так что лучше использовать всё сразу: и кнопки, и заготовленные комбинации.

2020-09-25 06:02 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/view/scene/twoDModelScene.cpp
> +	if (event->key() == Qt::Key_Delete || event->key() == Qt::Key_Backspace) {
См. следующий комментарий. Обрати внимание, что парой строк ниже https://github.com/trikset/trik-studio/pull/1118/files#diff-12a482364bb2116245c446207b0cb685L652 используется match, а не сравнение с конкретным значением. Здесь надо как-то так же.

2020-11-12 05:11 UTC, khodand commented
Надо как-то проверить на маке @iakov

2020-11-12 19:29 UTC, iakov approved these changes

2020-11-12 19:29 UTC, merged