Scroll features
trikset/trik-studio pull request #1144
Opened 2020-10-23 19:20 UTC by IKhonakhbeeva

Fixed #1113 
(Правда, я не нашла, как отличить мышь от тачпада, так что если кто-то вдруг захочет с зажатым шифтом передвигать сцену движениями на тачпаде, он немного удивится)

2020-10-23 19:41 UTC, iakov requested changes

2020-10-23 19:41 UTC, iakov commented on qrutils/graphicsUtils/abstractItemView.cpp
> +		auto newEvent = new QWheelEvent(event->pos(), event->globalPos(), QPoint()
Тут нет утечки?

2020-10-23 19:41 UTC, iakov commented on qrutils/graphicsUtils/abstractItemView.cpp
> +		event->accept();
А не надо делать accept до вызова wheelEvent(newEvent)?

2020-10-23 19:41 UTC, iakov commented on qrutils/graphicsUtils/abstractItemView.cpp
> +		auto newEvent = new QWheelEvent(event->pos(), event->globalPos(), QPoint()
Вообще, тут интересно с точки зрения архитектуры. Мне кажется, что контрол, у которого есть скроллбары должен просто передать это событие соответствующему скроллбару, что и происходит при обычном прокручивании колёсика. То есть тут надо просто при нажатом Shift передать событие горизонтальному скроллбару.

2020-10-23 19:41 UTC, iakov commented on qrutils/graphicsUtils/abstractItemView.cpp
> +		auto newEvent = new QWheelEvent(event->pos(), event->globalPos(), QPoint()
О! Нашёл пример. https://stackoverflow.com/questions/16475548/qgraphicsview-horizontal-scrolling-always-has-a-vertical-delta

2020-10-23 19:45 UTC, IKhonakhbeeva commented on qrutils/graphicsUtils/abstractItemView.cpp
> +		auto newEvent = new QWheelEvent(event->pos(), event->globalPos(), QPoint()
Кхм. Я пыталась сделать как-то разумно и понимала, что вот должно же быть как-то адекватно. Таки подплывший мозг дает о себе знать:)

2020-10-24 05:59 UTC, iakov approved these changes

2020-10-24 05:59 UTC, merged