Python version minor in test.sh
trikset/trik-studio pull request #1215
Opened 2020-12-24 12:21 UTC by khodand

2020-12-24 13:03 UTC, iakov requested changes

2020-12-24 13:03 UTC, iakov commented on buildScripts/azure/test.sh
> +[[ -n ${TRIK_PYTHON3_VERSION_MINOR:-} ]] || export TRIK_PYTHON3_VERSION_MINOR="$(python3 -V | sed 's#^Python [0-9]\.\([0-9]\)\.[0-9]*$#\1#g')" ;
https://stackoverflow.com/a/13864829

2020-12-24 13:03 UTC, iakov commented on buildScripts/azure/test.sh
> +[[ -n ${TRIK_PYTHON3_VERSION_MINOR:-} ]] || export TRIK_PYTHON3_VERSION_MINOR="$(python3 -V | sed 's#^Python [0-9]\.\([0-9]\)\.[0-9]*$#\1#g')" ;
Надо правильно проверять условие

2020-12-24 19:20 UTC, khodand commented on azure-pipelines.yml
> +  BUILD_TIMEOUT: 120
```suggestion
  BUILD_TIMEOUT: 2800
```

2020-12-24 21:57 UTC, khodand commented on buildScripts/azure/test.sh
> +if [ ! -z ${TRIK_PYTHON3_VERSION_MINOR+x} ]; then export TRIK_PYTHON3_VERSION_MINOR="$(python3 -V | sed 's#^Python [0-9]\.\([0-9]\)\.[0-9]*$#\1#g')"; fi
```suggestion
if [ $AGENT_OS = Darwin ]; then export TRIK_PYTHON3_VERSION_MINOR="$(python3 -V | sed 's#^Python [0-9]\.\([0-9]\)\.[0-9]*$#\1#g')"; fi
```

2020-12-25 11:02 UTC, iakov approved these changes

2020-12-25 11:02 UTC, merged