Support patching world without robot settings
trikset/trik-studio pull request #1267
Opened 2021-02-15 18:56 UTC by anastasiia-kornilova

Fix #1263

2021-02-15 19:40 UTC, iakov approved these changes

2021-02-16 12:04 UTC, IKhonakhbeeva requested changes
Стартовая позиция идет в комплекте с роботом в сейве, мы ее тут тоже оставляем, хотя ожидаемое поведение - позиция загружается вместе с полем
Чтобы не было проблем с разным поведением (патчер/сама студия) в идеале скопипастить код метода loadWorldModelWithoutRobot (из twoDModelWidget.cpp)

И второе - не стоит ли добавить защиту от дурака и запретить одновременный ввод -w и -f?

2021-02-16 15:09 UTC, anastasiia-kornilova commented
@IKhonakhbeeva, спасибо за фидбек, да про стартовую позицию я пропустила.
Правильно ли я понимаю, что `position` в `<robot position="-25:-25" .. >` измеряется относительно стартовой?

Про f и w -- да, можно добавить.

2021-02-16 18:45 UTC, iakov requested changes

2021-02-16 18:45 UTC, iakov commented on plugins/robots/checker/patcher/main.cpp
> +	// a ^ b ? c : a
`a + b + c >1` for bool should work fine.

2021-02-16 18:52 UTC, merged

2021-02-16 18:57 UTC, IKhonakhbeeva approved these changes