Add directory for junior examples
trikset/trik-studio pull request #1318
Opened 2021-04-06 12:52 UTC by IKhonakhbeeva

2021-04-08 15:07 UTC, iakov requested changes
Добавь, плиз, поддержку мака в инсталлятор, просто по аналогии из студии, я потом подправлю, если что не так. 
И убери, плиз, пока два самых тяжёлых файла, не место им тут пока.

2021-04-14 12:22 UTC, IKhonakhbeeva commented
Инсталлер на маке вроде собирается
Он в чем-то нерабочий? Если да, то в чем?

2021-04-16 07:38 UTC, iakov commented
Странный глюк на аппвейоре, такое же было недавно с рантаймом. Попробуй убрать `-j2` тут https://github.com/trikset/trik-studio/blob/junior/appveyor.yml#L160 , вдруг получится...

2021-04-16 07:39 UTC, iakov requested changes
Билд пока не проходит.

2021-04-27 06:18 UTC, iakov approved these changes

2021-04-27 06:19 UTC, merged