Add tests
trikset/trik-studio pull request #1340
Opened 2021-06-02 23:33 UTC by IKhonakhbeeva

2021-06-03 11:27 UTC, iakov requested changes

2021-06-03 11:27 UTC, iakov commented on .github/workflows/main.yml
>          continue-on-error: true
Почему без таймаута и зачем continue-on-error?

2021-06-03 11:27 UTC, iakov commented on buildScripts/tests/fieldstest.py
> -		print("Test %s. " % f + "Return code : %d. " % output.returncode + "Message: %s" % output.stderr)
Лучше, наверное, f-string использовать, понятнее будет.

2021-06-03 11:27 UTC, iakov commented on buildScripts/tests/fieldstest.py
> +		print()
Странная магия, вообще не понимаю без комментария.

2021-06-03 11:27 UTC, iakov commented on installer/reinstall-trik-studio.cmd
> +START /W %INSTALLER_EXE% --script "%TRIK_STUDIO_INSTALL_SCRIPT%"
А в чём разница? Вроде бы должно одинаково работать, когда под `cmd`.

2021-06-03 23:40 UTC, IKhonakhbeeva commented on installer/reinstall-trik-studio.cmd
> +START /W %INSTALLER_EXE% --script "%TRIK_STUDIO_INSTALL_SCRIPT%"
START /W заставляет ждать окончания процесса, а с какого-то момента qtifw стал порождать инсталлеры, которые обязательно фоном запускаются

2021-06-03 23:40 UTC, IKhonakhbeeva commented on buildScripts/tests/fieldstest.py
> +		print()
Просто вывод пустой строки
Можно заменить на ------

2021-06-03 23:43 UTC, IKhonakhbeeva commented on .github/workflows/main.yml
>          continue-on-error: true
continue-on-error - чтобы все равно сделать инсталлер и иметь возможность ручками посмотреть, что не так
Таймаут - не без, а заменен на 2 минуты вместо трех (в реальности тесты примерно одну минуту занимают, но беру с сзапасом)

2021-06-04 10:28 UTC, iakov commented on .github/workflows/main.yml
>          continue-on-error: true
А статус всего билда будет с ошибкой? Или билд будет считаться корректным?

2021-06-04 11:07 UTC, IKhonakhbeeva commented on .github/workflows/main.yml
>          continue-on-error: true
Блин
Статус всего билда будет прошедшим, только у билда добавится что-то формата "Annotations: 1 error"
Сейчас посмотрю, что можно более красивого и удобного сделать

2021-06-04 11:13 UTC, IKhonakhbeeva commented on buildScripts/tests/fieldstest.py
> -		print("Test %s. " % f + "Return code : %d. " % output.returncode + "Message: %s" % output.stderr)
Я разделила эту одну строчку на несколько, так значительно более читабельно выходит

2021-06-07 20:23 UTC, iakov approved these changes

2021-06-07 20:24 UTC, merged