Fix inputsCount for black box after finish
trikset/trik-studio pull request #1356
Opened 2021-06-30 11:49 UTC by IKhonakhbeeva

2021-07-02 07:22 UTC, iakov requested changes

2021-07-02 07:22 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/model/robotModel.cpp
> +		auto && ahead = aheadRect();
```suggestion
		const auto &ahead = aheadRect();
```

2021-07-02 07:22 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/model/robotModel.cpp
> +		auto && ahead = aheadRect();
ЕМНИП, ссылка `&&` умрёт в конце оператора на ';'

2021-07-06 20:59 UTC, IKhonakhbeeva commented on plugins/robots/common/twoDModel/src/engine/model/robotModel.cpp
> +		auto && ahead = aheadRect();
ahead не константный, он дальше меняется

2021-07-08 06:42 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/model/robotModel.cpp
> +		auto && ahead = aheadRect();
Ну тогда все равно не `&&`, а просто `auto`

2021-07-09 19:17 UTC, iakov approved these changes

2021-07-09 19:17 UTC, merged