Add CheckApp to installer
trikset/trik-studio pull request #1387
Opened 2021-07-26 12:52 UTC by iakov

2021-07-26 13:13 UTC, khodand approved these changes
Он же уже и так устанавливался вроде через инсталлер или я что-то не понимаю

2021-07-26 14:05 UTC, khodand requested changes

2021-07-26 14:05 UTC, khodand commented on installer/packages/trik-studio/ru.qreal.root.trik.core/meta/prebuild-linux-gnu.sh
> +cp     "$BIN_DIR"/{system.js,TRIK.py,2D-model,checkapp}            			"PWD/../data/bin/"
```suggestion
cp     "$BIN_DIR"/{system.js,TRIK.py,2D-model,checkapp}            			"$PWD/../data/bin/"
```

2021-07-26 15:23 UTC, iakov commented
Да, не посмотрел на винде. Будем считать, я перенёс его ближе к тулу запуска (2D-runner)

2021-07-26 15:24 UTC, khodand approved these changes

2021-07-28 11:14 UTC, khodand approved these changes

2021-07-28 12:57 UTC, merged