Lidar
trikset/trik-studio pull request #1434
Opened 2021-09-30 23:20 UTC by IKhonakhbeeva

Пример qrs-ки на то, чтобы поизучать поведение (нужно заменить расширение файла обратно на qrs) [lidar.zip](https://github.com/trikset/trik-studio/files/7263000/lidar.zip)

2021-10-02 16:21 UTC, iakov approved these changes

2021-10-02 16:21 UTC, iakov commented on plugins/robots/common/twoDModel/src/engine/view/scene/sensorItem.cpp
> +		return "range";
А вместо этих `else if` нельзя возвращать `sensor->name()`?

2021-12-03 18:29 UTC, iakov requested changes

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/src/trikbrick.cpp
> +	return mSensors.keys();
Ого! И раньше же не мешало, похоже :)

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/src/trikbrick.cpp
> +		robotParts::VectorSensor * lidar =
`auto *lidar = ...`?

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/src/trikbrick.cpp
> +		if (lidar == nullptr) {
`if (!lidar)`?

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/src/trikEmulation/triklidaremu.cpp
> +	QMetaObject::invokeMethod(mLidar, "read");
Мы хотим блокировать и подождать? Или хотим именно инициировать асинхронный вызов?
Лучше методы вызывать по указателю, а не по имени, если есть соответствующая сигнатура

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/include/trikKitInterpreterCommon/trikEmulation/triklidaremu.h
> +	TrikLidarEmu(kitBase::robotModel::robotParts::VectorSensor *lidar);
`explicit TrikLidarEmu`?

2021-12-03 18:29 UTC, iakov commented on plugins/robots/interpreters/trikKitInterpreterCommon/include/trikKitInterpreterCommon/trikEmulation/triklidaremu.h
> +	kitBase::robotModel::robotParts::VectorSensor *mLidar;
Лучше делать инициализацию через `{}`, это не помешает. А кто тут владелец объекта? Надо бы комментарием указать, если нет владения.

2021-12-18 13:48 UTC, iakov commented
Нужно ещё :
1. [ ] взять последний рантайм
2. [ ] удовлетворить Веру.

2021-12-19 17:33 UTC, IKhonakhbeeva commented
Сделано

2021-12-20 11:19 UTC, iakov approved these changes

2021-12-20 11:20 UTC, merged